config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users, only: [:show, :index] do
    resources :evaluations, except: [:show, :index]
  end
  resources :projects do
    post 'karma'
    resources :positions, except: [:index] do
      post 'add_user'
      post 'remove_user'
    end
    resources :comments do
      post 'karma'
    end
    get 'my', on: :collection
    get 'participating', on: :collection
  end

  resources :positions, only: [:index] do
    get 'empty', on: :collection
    get 'my', on: :collection
  end

  resources :messages, except: [:index, :update, :edit] do
    get 'received', on: :collection
    get 'sent', on: :collection
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  resourcify

  attr_accessor :to_name

  belongs_to :from, class_name: 'User'
  belongs_to :to, class_name: 'User'
  belongs_to :user

  validates :from, presence: true
  validates :to, presence: true
  validates :text, presence: true
  validates :send_time, presence: true
  validates :to_name, user_exist: true

  def to_name=(name)
    self.to = User.find_by name: name
    @to_name = name
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  load_and_authorize_resource
  before_action :set_message, only: [:show, :destroy]

  def received
    @messages = current_user.received_messages
    render :index
  end

  def sent
    @messages = current_user.sent_messages
    render :index
  end

  def new
    @message = Message.new
  end

  def show
    session[:prev_url] = request.referer
    unless @message.read_time
      @message.update_attribute(:read_time, Time.now)
    end
  end

  def create
    @message = Message.new(message_params)
    @message_received = Message.new(message_params)

    recipient = @message.to

    @message.user = current_user
    @message.from = current_user
    @message.send_time = Time.now
    @message.read_time = Time.now
    @message.subject = '---No subject---' if @message.subject.blank?

    @message_received.user = recipient
    @message_received.from = current_user
    @message_received.send_time = Time.now
    @message_received.subject = '---No subject---' if @message_received.subject.blank?

    respond_to do |format|
      if @message.save && @message_received.save && current_user.add_role(:owner, @message) && recipient.add_role(:owner, @message_received)
        format.html { redirect_to :received_messages, notice: 'Message was sent.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to session[:prev_url] ? session[:prev_url] : :back, notice: 'Message was deleted.' }
    end
  end

  private

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:text, :to_name, :subject)
  end
end

app/views/messages/index.html.slim
div class="container"
  = link_to "Received", :received_messages, class: 'sub-menu-link'
  = link_to "Sent", :sent_messages, class: 'sub-menu-link'
  = link_to new_message_path, class: 'pull-right btn btn-default button-margins' do
    span class="left-icon glyphicon glyphicon-plus"
    | New message

div class="container"
  .row
    h1
      = controller.action_name.capitalize

div class="container"
  div class="row"
    table class="table table-striped table-hover"
      thead
        tr
          - if controller.action_name == 'received'
            th class="col-md-2" From
          - else
            th class="col-md-2" To
          th Subject
          th class="col-md-2"
            = controller.action_name.capitalize
          th class="col-md-1"
      tbody
        - @messages.each do |message|
          tr class=(message.read_time ? "clickable-row": "clickable-row unread") data-href="#{message_path(message)}"
            - if controller.action_name == 'received'
              td
                = message.from.name
            - else
              td
                = message.to.name
            td
              = message.subject
            td
              = message.send_time
            td
              = link_to message, method: :delete, data: { confirm: "Are you sure?" } do
                span class="glyphicon glyphicon-trash"

app/views/messages/new.html.slim
div class="container"
  div class="row"
    h1 New message
    
  div class="row"
    = simple_form_for(@message) do |f|
      = f.error_notification
      .form-inputs
        = f.input :to_name, label: "To"
        = f.input :subject, as: :string
        = f.input :text
      .form-actions
        = f.button :submit, label: "Send message"
    
  div class="row"
    = link_to "Back", url_for(:back), class: 'btn btn-default button-margins'

app/views/messages/show.html.slim
div class="container"
  div class="row"
    h1 Message
    
  div class="row"
    p Subject: #{@message.subject}
    p From: #{@message.from.name}
    p To: #{@message.to.name}
    p Date: #{@message.send_time}
    p
      = @message.text
  
  div class="row"
    = link_to "Back", url_for(:back), class: 'btn btn-default button-margins'
    = link_to "Delete", @message, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-default button-margins'
    