config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users, only: [:show, :index] do
    resources :evaluations, except: [:show, :index]
  end
  resources :projects do
    post 'karma'
    resources :positions, except: [:index] do
      post 'add_user'
      post 'remove_user'
    end
    resources :comments do
      post 'karma'
    end
    get 'my', on: :collection
    get 'participating', on: :collection
  end

  resources :positions, only: [:index] do
    get 'empty', on: :collection
    get 'my', on: :collection
  end

  resources :messages, except: [:index, :update, :edit] do
    get 'received', on: :collection
    get 'sent', on: :collection
  end

end

app/models/position.rb
class Position < ActiveRecord::Base
  resourcify
  
  belongs_to :project
  belongs_to :user
  belongs_to :contract
  has_many :skills

  validates :project, presence: true
  validates :contract_id, presence: true

  acts_as_taggable_on :skills
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  load_and_authorize_resource :project, except: [:index, :show, :my, :empty]
  load_and_authorize_resource :position, :through => :project, except: [:index, :show, :add_user, :remove_user, :my, :empty]
  load_and_authorize_resource :position, only: [:index, :show, :add_user, :remove_user]
  before_action :set_position, only: [:show, :edit, :update, :destroy]
  before_action :set_contracts, only: [:index, :edit, :new, :show]
  before_action :set_add_user_position, only: [:add_user, :remove_user]
  before_action :set_users_positions, only: [:remove_user]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.includes(:skills)
    @positions = @positions.order(:name).page(params[:page])
  end

  def empty
    @positions = Position.where(user: nil).includes(:skills)
    @positions = @positions.order(:name).page(params[:page])
    render :index
  end

  def my
    @positions = Position.where(user: current_user).includes(:skills)
    @positions = @positions.order(:name).page(params[:page])
    render :index
  end
  # GET /positions/1
  # GET /positions/1.json
  def show
    position_id = params[:id]
    @project = Project.find(params[:project_id])
    @position = Position.includes(:skills).find(position_id)
    @user = User.where('user.id = ?', @position.user_id)
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  def add_user
    @position.user = current_user
    @position.save
    render :show
  end

  def remove_user
    @position.user = nil
    @position.save
    render :show
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)
    @project = Project.find(params[:project_id])
    @position.project = @project

    respond_to do |format|
      if @position.save && current_user.add_role(:owner, @position)
        format.html { redirect_to @project, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    @project = Project.find(params[:project_id])
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to project_position_url(@project,@position), notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    def set_add_user_position
      @position = Position.find(params[:position_id])
    end

    def set_previous_url
      session[:prev_url] = request.referer
    end

    def set_users_positions
      @positions = Position.where('user_id = ?',current_user.id)
    end

    def set_contracts
      @contracts = Contract.all.order('contracts.name')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params[:position].permit(:name, :contract_id, :description, :skill_list)
    end
end

app/views/positions/edit.html.slim
.container
  .row
    h1 Editing position

  .row
    = simple_form_for(@position, url: project_position_path(@project, @position.id)) do |f|
      = f.error_notification

      .form-inputs
        = f.input :name
        = f.input :description
        = f.input :contract_id, collection: @contracts, label_method: :name, value_method: :id, include_blank: false
        = f.hidden_field :skill_list, value: @position.skill_list.join(','), id: 'skill_list'
        div class="form-group"
          = label @position.name, :skill_list, "Skills", class: "control-label"
          div class="add-skill-input"
            a href='#' id="add-skill-link" class="btn btn-default" aria-hidden="true"
              span class="glyphicon glyphicon-plus"
                | Add skill
            = text_field_tag(:new_skill)
          div class="skills"
            - @position.skill_list.each do |skill|
              div class="skill btn btn-primary btn-sm"
                span
                  = skill
                a href='#' class="remove-skill-link" aria-hidden="true"
                  span class="glyphicon glyphicon-remove"

      .form-actions
        = f.button :submit, label: "Edit Position"

  .row
    = link_to "Back", url_for(:back)

app/views/positions/index.html.slim
h1 Positions

h3 Filter positions
div class="btn-group"
  = link_to :positions, class: 'btn btn-default btn-lg' do
    span class="left-icon glyphicon glyphicon-th-list"
    | All positions
  = link_to :empty_positions, class: 'btn btn-default btn-lg' do
    span class="left-icon glyphicon glyphicon-screenshot"
    | Empty positions
  = link_to :my_positions, class: 'btn btn-default btn-lg' do
    span class="left-icon glyphicon glyphicon-user"
    | My positions
br
div class="container"
  br
  div class="row"
    table class="table table-striped table-hover"
      thead
        tr
          th class="col-md-2" Position
          th class="col-md-1" Locality
          th class="col-md-2" Project
          th class="col-md-1" Contract
          th Skills
          th class="col-md-2" Assigned to
      tbody
        - @positions.each do |position|
          tr class="clickable-row" data-href="#{project_position_path(position.project, position)}"
            td
              strong
                = position.name
            td
              = position.project.locality
            td
              = position.project.name
            td
              = position.contract.name
            td class="skills"
              - position.skill_list.each do |skill|
                div class="skill btn btn-primary btn-sm"
                  = skill
            td
              - if position.user
                = position.user.name
              - else
               e free

br
=paginate @positions

app/views/positions/new.html.slim
.container
  .row
    h1 New position

  .row
    = simple_form_for(@position, url: project_positions_path(@project.id), html: {methos: :put}) do |f|
      = f.error_notification

      .form-inputs
        = f.input :name
        = f.input :description
        = f.input :contract_id, collection: @contracts, label_method: :name, value_method: :id, include_blank: false
        = f.hidden_field :skill_list, value: @position.skill_list.join(','), id: 'skill_list'
        div class="form-group"
          = label @position.name, :skill_list, "Skills", class: "control-label"
          div class="add-skill-input"
            a href='#' id="add-skill-link" class="btn btn-default" aria-hidden="true"
              span class="glyphicon glyphicon-plus"
                | Add skill
            = text_field_tag(:new_skill)
          div class="skills"
            - @position.skill_list.each do |skill|
              div class="skill btn btn-primary btn-sm"
                span
                  = skill
                a href='#' class="remove-skill-link" aria-hidden="true"
                  span class="glyphicon glyphicon-remove"

      .form-actions
        = f.button :submit, label: "Create Position"
  .row
    = link_to "Back", url_for(:back)

app/views/positions/show.html.slim
p#notice = notice

.row
  div class="col-md-4"
    h2
      = @position.name
    div class="btn-toolbar"
      -  if can? :update, @position
        = link_to 'Edit', edit_project_position_path(@project, @position), class: 'btn btn-default pull-left'
        = link_to 'Delete', [@project, @position], method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-default pull-left'
      = link_to 'Back', url_for(:back), class: 'btn btn-default pull-left'
  div class="col-md-8"
    h3 Description:
    p
      = @position.description
    h3 Required skills
    - if @position.skill_list.empty?
      p Position does not have required skills.
    - else
      div class="skills"
        - @position.skill_list.each do |skill|
          div class="skill btn btn-primary btn-sm"
            = skill
    h3 Contract type:
    p
      = @position.contract.name
    h3 Position assignee:
    - if !@position.user
      = link_to 'Not assigned yet. Apply?', project_position_add_user_path(@project, @position.id), method: :post, class: 'btn btn-default'
    - else
      = link_to user_path(@position.user) do
        span aria-hidden="true"
          span
            = image_tag(@position.user.avatar.url(:tiny))
          span
            = @position.user.name
    - if @position.user == current_user
      div class="btn-toolbar"
        = link_to 'Abandon Position', project_position_remove_user_path(@project, @position.id), method: :post, class: 'btn btn-default pull-left button-margins'