config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users, only: [:show, :index] do
    resources :evaluations, except: [:show, :index]
  end
  resources :projects do
    post 'karma'
    resources :positions, except: [:index] do
      post 'add_user'
      post 'remove_user'
    end
    resources :comments do
      post 'karma'
    end
    get 'my', on: :collection
    get 'participating', on: :collection
  end

  resources :positions, only: [:index] do
    get 'empty', on: :collection
    get 'my', on: :collection
  end

  resources :messages, except: [:index, :update, :edit] do
    get 'received', on: :collection
    get 'sent', on: :collection
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  resourcify
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :skills
  has_many :positions
  has_many :own_projects, class_name: 'Project', foreign_key: 'author_id'
  has_many :other_projects, class_name: 'Project', through: :positions, source: :project
  has_many :evaluations
  has_many :messages

  validates :name, presence: true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", tiny: '30x30' }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  acts_as_taggable_on :skills

  scope :confirmed, -> { where('confirmed_at IS NOT NULL') }

  def project_count
    Project.where('author_id = ?', id).count + Position.select(:project_id).distinct.includes(:project).references(:project).where('user_id = ? and projects.author_id != ?', id, id).count
  end

  def sent_messages
    Message.includes(:user).where('messages.user_id = ? and messages.from_id = ?', id, id)
  end

  def received_messages
    Message.includes(:user).where('messages.user_id = ? and messages.to_id = ?', id, id)
  end

  def unread_messages
    Message.where('messages.user_id = ? and messages.to_id = ? and messages.read_time is ?', id, id, nil).count('id')
  end

  def self.name_like(name)
    where("name LIKE ?", "%#{name}%")
  end

  def self.locality_like(locality)
    where("locality LIKE ?", "%#{locality}%")
  end

  def self.skills_like(skills)
    array = []
    array = skills.split(',') if skills
    array.map! { |skill| skill.strip }
    tagged_with(array, :any => true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.confirmed.includes(:skills)
    @users = @users.name_like(params[:search_name]) unless params[:search_name].blank?
    @users = @users.locality_like(params[:search_locality]) unless params[:search_locality].blank?
    @users = @users.skills_like(params[:search_skills]) unless params[:search_skills].blank?
    @users = @users.order(:name).page(params[:page])
  end

  def show
    user_id = params[:id]
    @user = User.confirmed.includes(:skills).includes(:evaluations).find(user_id)
    @projects = Project.includes(:karmas)
    .includes(:participants)
    .references(:positions)
    .where('positions.user_id = ? or projects.author_id = ?', user_id, user_id)
  end
end

app/views/users/index.html.slim
h1 Users
div class="container"
  div class="row search"
    = form_tag users_path, method: :get do
      = label :search, :name, "Name"
      = text_field_tag(:search_name)
      = label :search, :locality, "Locality"
      = text_field_tag(:search_locality)
      = label :search, :skills, "Skills"
      = text_field_tag(:search_skills)
      = submit_tag "Search", :name => nil, :class => "btn btn-default"
div class="container"
  div class="row"
    table class="table table-striped table-hover"
      thead
        tr
          th class="col-md-2" Name
          th class="col-md-2" Locality
          th Skills
          th class="col-md-2" Number of projects
      tbody
        - @users.each do |user|
          tr class="clickable-row" data-href="#{user_path(user)}"
              td
                span class="left-icon"
                  = image_tag(user.avatar.url(:tiny))
                span
                  strong
                    = user.name
              td
                = user.locality
              td class="skills"
                - user.skill_list.each do |skill|
                  div class="skill btn btn-primary btn-sm"
                    = skill
              td
                = user.project_count

= paginate @users

app/views/users/show.html.slim
  div class="row user"
    div class="col-md-4"
      = image_tag(@user.avatar.url(:medium))
      h4
       = @user.name
      div aria-hidden="true"
        span class="left-icon glyphicon glyphicon-time"
        | Joined on #{@user.confirmed_at}
      - unless @user.locality.blank?
        div aria-hidden="true"
          span class="left-icon glyphicon glyphicon-map-marker"
          | Working from #{@user.locality}
    
    div class="col-md-8"
      h2 Projects
      - if @projects.empty?
        p User is not involved in any projects
      - else
        ul class="projects"
          - @projects.each do |project|
            li class="project"
              = link_to project_path(project) do
                div class="texts"
                  div class="name pull-left"
                    = project.name
                  div class="description pull-left"
                    = project.description
                div class="icons"
                  span aria-hidden="true" class="participants"
                    = Project.number_of_participants(project.id)
                    span class="glyphicon glyphicon-user right-icon"
                  span aria-hidden="true" class="karma"
                    = project.karmas.count
                    span class="glyphicon glyphicon-star right-icon"
      
      h2 Skills
      - if @user.skill_list.empty?
        p User doesn't have any skills
      - else
        div class="skills"
          - @user.skill_list.each do |skill|
            div class="skill btn btn-primary btn-sm"
              = skill
      
      h2 Evaluations
      - if @user.evaluations.empty?
        p User have no evaluations
      - else
        div class="evaluations"
          - @user.evaluations.each do |evaluation|
            div class="evaluation row"
              span class="col-md-3"
                div
                  span class= "author" Author:
                  = link_to evaluation.author.name, user_path(evaluation.author)
                div
                  span class="project" Project:
                  = link_to evaluation.project.name, project_path(evaluation.project)
              span class="col-md-8"
                = evaluation.text
              span class="col-md-1"
                - if can? :update, evaluation
                  = link_to edit_user_evaluation_path(@user.id, evaluation.id), class: "block-icon" do
                    span class="glyphicon glyphicon-edit"
                - if can? :destroy, evaluation
                  = link_to user_evaluation_path(@user.id, evaluation.id), method: :delete, data: { confirm: "Are you sure?" }, class: "block-icon" do
                    span class="glyphicon glyphicon-trash"
      = link_to new_user_evaluation_path(@user.id), class: (@projects.empty? ? 'pull-right btn btn-default disabled' : 'pull-right btn btn-default') do
        span class="left-icon glyphicon glyphicon-plus"
        | Add evaluation