config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users, only: [:show, :index] do
    resources :evaluations, except: [:show, :index]
  end
  resources :projects do
    post 'karma'
    resources :positions, except: [:index] do
      post 'add_user'
      post 'remove_user'
    end
    resources :comments do
      post 'karma'
    end
    get 'my', on: :collection
    get 'participating', on: :collection
  end

  resources :positions, only: [:index] do
    get 'empty', on: :collection
    get 'my', on: :collection
  end

  resources :messages, except: [:index, :update, :edit] do
    get 'received', on: :collection
    get 'sent', on: :collection
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  resourcify

  belongs_to :author, class_name: 'User'
  has_many :positions, dependent: :destroy
  has_many :participants, class_name: 'User', through: :positions, source: :user
  has_many :comments, dependent: :destroy
  has_many :karmas, as: :karmable, dependent: :destroy

  validates :author, presence: true
  validates :name, presence: true

  def self.number_of_participants(id)
    Project.find(id).participants.distinct.count
  end

  def self.name_like(name)
    where("name LIKE ?", "%#{name}%")
  end

  def self.author_like(author)
    where("author LIKE ?", "%#{author}%")
  end

  def self.locality_like(locality)
    where("locality LIKE ?", "%#{locality}%")
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_action :set_project, only: [:show, :edit, :update, :destroy, :karma]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @projects = @projects.name_like(params[:filter_name]) unless params[:filter_name].blank?
    @projects = @projects.author_like(params[:filter_author]) unless params[:filter_author].blank?
    @projects = @projects.locality_like(params[:filter_locality]) unless params[:filter_locality].blank?
    @projects = @projects.order(:name).page(params[:page])
  end

  def my
    @projects = current_user.own_projects
    @projects = @projects.order(:name).page(params[:page])
    render :index
  end

  def participating
    @projects = current_user.other_projects
    @projects = @projects.order(:name).page(params[:page])
    render :index
  end

  def create_position
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    project_id = params[:id]
    @project = Project.find(project_id)
    @positions = Position.includes(:skills)
    .where('positions_id = ?', project_id)
    @karma = Karma.find_by(author: current_user, karmable: @project)
  end

  # GET /projects/new
  def new
    @project = current_user.own_projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.own_projects.build(project_params)

    respond_to do |format|
      if @project.save && @project.author.add_role(:owner, @project)
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def karma
    @karma = Karma.find_by(author: current_user, karmable: @project)
    if @karma
      @karma.destroy
    else
      @karma = Karma.new
      @karma.author = current_user
      @karma.karmable = @project

      @karma.save && @karma.author.add_role(:owner, @karma)
    end

    redirect_to @project
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      params[:id] ||= params[:project_id]
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name,:description,:locality)
    end
end

app/views/projects/_form.html.slim
= simple_form_for(@project) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :locality
  .form-actions
    = f.button :submit

app/views/projects/edit.html.slim
h1 Editing project

== render 'form'

= link_to 'Show', @project
'|
= link_to 'Back', projects_path

app/views/projects/index.html.slim
.row
  h1 class="pull-left" Projects
  = link_to new_project_path, class: 'pull-right btn btn-default button-margins' do
    span class="left-icon glyphicon glyphicon-plus"
    | New project

.row
  div class="btn-group"
    = link_to :projects, class: 'btn btn-default btn-lg' do
      span class="left-icon glyphicon glyphicon-th-list"
      | All projects
    = link_to :my_projects, class: 'btn btn-default btn-lg' do
      span class="left-icon glyphicon glyphicon-king"
      | My projects
    = link_to :participating_projects, class: 'pull-right btn btn-default btn-lg' do
      span class="left-icon glyphicon glyphicon-pawn"
      | Projects participating on

.row
  .search
    = form_tag projects_path, method: :get do
      = label :search, :name, "Name"
      = text_field_tag(:filter_name)
      = label :search, :author, "Author"
      = text_field_tag(:filter_author)
      = label :search, :locality, "Locality"
      = text_field_tag(:filter_locality)
      = submit_tag "Search", :name => nil, :class => "btn btn-default"
      
.row
  ul class="projects"
    - @projects.each do |project|
      li
        = link_to project do
          div class="col-md-9"
            div class="name"
              strong
                = project.name
            div class="description"
              = project.description
          div class="col-md-3"
            - unless project.locality.blank?
              div
                span class="left-icon glyphicon glyphicon-map-marker" title="Locality"
                = project.locality
            div
              span class="left-icon glyphicon glyphicon-king" title="Author"
              = project.author.name
            div
              span class="left-icon glyphicon glyphicon-star" title="Karma"
              = project.karmas.count

=paginate @projects

app/views/projects/new.html.slim
h1 New project

== render 'form'

= link_to 'Back', projects_path, class: 'btn btn-default button-margins'

app/views/projects/show.html.slim
p#notice = notice

.row
  div class="col-md-4"
    h1
      = @project.name
    div aria-hidden="true"
      span class="left-icon glyphicon glyphicon-king"
      | Author: 
      = link_to user_path(@project.author) do 
        = @project.author.name
    - unless @project.locality.blank?
      div aria-hidden="true"
        span class="left-icon glyphicon glyphicon-map-marker"
        | Located at #{@project.locality}
      = button_to project_karma_path(@project.id), method: :post, class: "btn btn-default btn-xs pull-left" do
        span aria-hidden="true"
          - if @karma
            span class="glyphicon glyphicon-minus left-icon"
            | Karma
          - else
            span class="glyphicon glyphicon-plus left-icon"
            | Karma
      span class="pull-left right-icon"
        = @project.karmas.count

  div class="col-md-8"
    h3
      = @project.description
    
    h3 Positions
    table class="table table-striped table-hover positions"
      thead
        tr
          th class="col-md-2" Name
          th class="col-md-3" Description
          th Skills
          th class="col-md-2" Assignee
      tbody
        - @project.positions.each do |position|
          tr class="clickable-row" data-href="#{project_position_path(@project, position)}"
            td
              strong
                = position.name
            td
              strong
                = position.description
            td class="skills"
              - position.skill_list.each do |skill|
                div class="skill btn btn-primary btn-sm"
                  = skill
            td
              - if !position.user
                p Not assigned yet
              - else
                = position.user.name
    - if current_user.has_role? :owner, @project
      = link_to new_project_position_path(@project.id), class: 'btn btn-default pull-right' do
        span class="left-icon glyphicon glyphicon-plus"
        | Create position

div class="row comments"
  h3 Comments
  - @project.comments.each do |comment|
    .row
      div class="col-md-2"
        div
          = comment.author.name
        div
          = comment.created_at
        - if can? :destroy, comment
          = link_to [ comment.project, comment ], method: :delete, data: { confirm: 'Are you sure?' }, class: "block-icon" do
            span class="glyphicon glyphicon-trash"
      div class="col-md-8"
        = comment.text
      div class="col-md-2"
        = button_to project_comment_karma_path(@project.id, comment.id), method: :post, class: "btn btn-default btn-xs pull-left" do
          div aria-hidden="true"
            - if comment.has_karma?(current_user)
              span class="glyphicon glyphicon-minus left-icon"
              | Karma
            - else
              span class="glyphicon glyphicon-plus left-icon"
              | Karma
        span class="pull-left right-icon"
          = comment.karmas.count
        
div class="row new-comment"
  = simple_form_for( [@project, @project.comments.build] ) do |f|
    - if @comment && @comment.errors.any?
      - @comment.errors.full_messages.each do |msg|
        li class="text-danger"
          = msg
    .form-inputs
      = f.input :text
    .form-actions
      = f.button :submit, "Add comment"
  div class="btn-toolbar"
    = link_to 'Back', projects_path, class: 'btn btn-default button-margins'
    - if can? :update, @project
      = link_to 'Edit', edit_project_path(@project), class: 'btn btn-default button-margins'
      = link_to "Delete", @project, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-default button-margins'